import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv.includes("prod");
const isWatch = process.argv.includes("watch");

const buildConfig = {
    banner: {
        js: banner,
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    minify: isProd,
    format: "cjs",
    target: "es2018",
    logLevel: isProd ? "error" : "debug",
    sourcemap: !isProd,
    outfile: "./dist/main.js",
    plugins: [
        {
            name: "move-files-plugin",
            setup(build) {
                build.onEnd((result) => {
                    if (result.errors.length === 0) {
                        movePluginFiles();
                    } else {
                        console.error(
                            "Build failed with errors:",
                            result.errors
                        );
                    }
                });
            },
        },
    ],
};

// Copy the main.js and manifest.json to the test vault
function movePluginFiles() {
    const sourceMain = path.resolve("./dist/main.js");
    const sourceMainMap = path.resolve("./dist/main.js.map");
    const sourceManifest = path.resolve("./manifest.json");
    const destinationFolder = path.resolve(
        "./test/vault/test/.obsidian/plugins/s3-link-test/"
    );

    if (!fs.existsSync(destinationFolder)) {
        fs.mkdirSync(destinationFolder, { recursive: true });
    }

    fs.promises
        .copyFile(sourceMain, path.join(destinationFolder, "main.js"))
        .then(() => console.log("main.js moved successfully"))
        .catch((err) => console.error("Error moving main.js:", err));

    fs.promises
        .copyFile(sourceManifest, path.join(destinationFolder, "manifest.json"))
        .then(() => console.log("manifest.json moved successfully"))
        .catch((err) => console.error("Error moving manifest.json:", err));

    if (fs.existsSync(sourceMainMap)) {
        fs.promises
            .copyFile(
                sourceMainMap,
                path.join(destinationFolder, "main.js.map")
            )
            .then(() => console.log("main.js.map moved successfully"))
            .catch((err) => console.error("Error moving main.js.map:", err));
    }
}

async function build() {
    try {
        if (isWatch) {
            // Start watch mode
            const ctx = await esbuild.context(buildConfig);
            await ctx.watch();
            console.log("Watching for changes...");

            movePluginFiles();
        } else {
            // Single build for CI/CD
            await esbuild.build(buildConfig);
            console.log("Build complete.");
        }
    } catch (error) {
        console.error("Build failed:", error);
        process.exit(1);
    }
}

build();
