name: "Release GitHub"
on: [workflow_dispatch]

jobs:
  release-github:
    runs-on: ubuntu-latest
    name: GitHub Release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
