name: "Release GitHub"
on:
  push:
    tags:
      - "**"

env:
  PLUGIN_NAME: obsidian-plugin-s3-link

jobs:
  release-github:
    runs-on: ubuntu-latest
    name: GitHub Release
    steps:
      - name: "Release Tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: "Create release"
        run: |
          gh release create $RELEASE_TAG ${{ env.PLUGIN_NAME }}.zip main.js manifest.json --title $RELEASE_TAG --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
